### ISSUE TITLE
能否添加阅读次数功能？

### ISSUE THREAD

**Issue by flying-polarbear** [cotes2020/chirpy#1]
作者你好，
我准备借用你的模版弄个人博客，因为jekyll不是很熟练，所以请问能否加几个功能？
比如，
1: 首页底部统计整个网站的访问次数
2: 单篇文章的访问次数？？

谢谢！

**Comment by cotes2020** [comment]
关于访问次数的显示，博客已经有这个功能了，但Jekyll博客它只是一个静态页面，则需要你额外部署一个 [Google Analytics superProxy](https://github.com/googleanalytics/google-analytics-super-proxy) 到 App Engine 完成后端支持。然后在 `_data/settings.yml` 开启 `pv` 选项就 OK 了。

你可以看我的 [博客](https://blog.cotes.info/) 示例，首页列表和单篇文章内都有阅读次数显示。

另外，关于“整个网站的访问次数”这个是我个人觉得不需要显示而已，欢迎你Forked一份代码，然后在自己的版本小改一下显示出来。

**Comment by cotes2020** [comment]
> 作者你好，
> 我准备借用你的模版弄个人博客，因为jekyll不是很熟练，所以请问能否加几个功能？
> 比如，
> 1: 首页底部统计整个网站的访问次数
> 2: 单篇文章的访问次数？？
> 
> 谢谢！

关于访问次数的显示，博客已经有这个功能了，但Jekyll博客它只是一个静态页面，则需要你额外部署一个 [Google Analytics superProxy](https://github.com/googleanalytics/google-analytics-super-proxy) 到 App Engine 完成后端支持。然后在 `_data/settings.yml` 开启 `pv` 选项就 OK 了。

你可以看我的 [博客](https://blog.cotes.info/) 示例，首页列表和单篇文章内都有阅读次数显示。

另外，关于“整个网站的访问次数”这个是我个人觉得不需要显示而已，欢迎你Forked一份代码，然后在自己的版本小改一下显示出来。

**Comment by flying-polarbear** [comment]
谢谢回复，
搞定了！
